
name: Tests

on: [push]

jobs:

  test-runtime:
    runs-on: debian-latest
    strategy:
      matrix:
        runtime: [smol, tokio]
    steps:
      - uses: actions/checkout@v4

      - name: Update Rust to latest
        run: rustup update

      - name: Run ${{ matrix.runtime }} tests
        run: cargo test --no-default-features --features ${{ matrix.runtime }}
